plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':common')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-kafka'

    implementation 'org.springframework.boot:spring-boot-starter-opentelemetry'
    implementation 'io.opentelemetry.instrumentation:opentelemetry-logback-appender-1.0:2.21.0-alpha'
    implementation 'io.opentelemetry.instrumentation:opentelemetry-instrumentation-annotations:2.21.0'
    implementation 'org.springframework.boot:spring-boot-starter-aspectj'

    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
}


